version: '2.4'

services:
    notifier_api:
        build:
            context: ./src
        image: kpi_notifier:1.0.0
        networks:
            - proxy-redirect
        mem_limit: 100mb
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'

networks:
    proxy-redirect:
        external:
            name: proxy-redirect